name: Deploy Infrastructure (Development)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy-development:
    environment:
      name: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run Ansible playbook (Development)
        env:
          ANSIBLE_GRAFANA_ADMIN_USER: ${{ secrets.DEV_ANSIBLE_GRAFANA_ADMIN_USER }}
          ANSIBLE_GRAFANA_ADMIN_PASSWORD: ${{ secrets.DEV_ANSIBLE_GRAFANA_ADMIN_PASSWORD }}
          ANSIBLE_GRAFANA_PORT: ${{ secrets.DEV_ANSIBLE_GRAFANA_PORT }}
          
          ANSIBLE_USER: ${{ secrets.DEV_ANSIBLE_USER }}
          ANSIBLE_HOST: ${{ secrets.DEV_ANSIBLE_HOST }}
          ANSIBLE_PORT: ${{ secrets.DEV_ANSIBLE_PORT }}
          
          ANSIBLE_POSTGRESQL_ADMIN_USER: ${{ secrets.DEV_ANSIBLE_POSTGRESQL_ADMIN_USER }}
          ANSIBLE_POSTGRESQL_ADMIN_PASSWORD: ${{ secrets.DEV_ANSIBLE_POSTGRESQL_ADMIN_PASSWORD }}
          ANSIBLE_POSTGRESQL_ADMIN_DB: ${{ secrets.DEV_ANSIBLE_POSTGRESQL_ADMIN_DB }}
          ANSIBLE_POSTGRESQL_PORT: ${{ secrets.DEV_ANSIBLE_POSTGRESQL_PORT }}
          
          ANSIBLE_MINIO_SERVER_PORT: ${{ secrets.DEV_ANSIBLE_MINIO_PORT }}
          ANSIBLE_MINIO_CONSOLE_PORT: ${{ secrets.DEV_ANSIBLE_MINIO_CONSOLE_PORT }}
          ANSIBLE_MINIO_ROOT_USER: ${{ secrets.DEV_ANSIBLE_MINIO_ROOT_USER }}
          ANSIBLE_MINIO_ROOT_PASSWORD: ${{ secrets.DEV_ANSIBLE_MINIO_ROOT_PASSWORD }}

          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i inventory.yml playbook.yml --private-key private_key.pem -u ${{ secrets.DEV_ANSIBLE_USER }} -e env=development

  notify:
    needs: [deploy-development]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Determine deployment status
        id: status
        run: |
          if [[ "${{ needs.deploy-development.result }}" == "success" ]]; then
            echo "status=âœ… Success" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.deploy-development.result }}" == "failure" ]]; then
            echo "status=âŒ Failed" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.deploy-development.result }}" == "skipped" ]]; then
            echo "status=â­ï¸ Skipped" >> $GITHUB_OUTPUT
          else
            echo "status=âš ï¸ Partial" >> $GITHUB_OUTPUT
          fi

      - name: Notify deployment status
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |

            ðŸ‘»*Author:* ${{ github.actor }}
            *Message:* `${{ github.event.head_commit.message }}`
            
            *Project:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Status:* ${{ steps.status.outputs.status }}
            *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            
            *Dev Deploy:* ${{ needs.deploy-development.result }}
